name: Auto-publish to npm when version changes
on: push

jobs:

  publish:
    name: Publish to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master') # Publish it only if the push comes from the master branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies, compile and prepare publish
        if: steps.check.outputs.changed == 'true'
        run: npm ci && npm run compile && npm run prepare-publish

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
